POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "name":"júllia", 
    "email":"jullia2@gmail.com",
    "password":"123"
}
###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"jullia@gmail.com",
    "password":"123"
}

###

POST http://localhost:3000/category/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.anVsbGlhQGdtYWlsLmNvbQ.-uf7sdhwtZej4vKvvpzQg-wv20FKxyhBY-rP3zbh_0g

{
    "name":"romance"
}